### PR TITLE
replaceEmpty only accepts values

### PR DESCRIPTION
**Pull request by kcramer**
Note that replaceEmpty does not accept a Publisher/obsverable as ifEmpty does.

### CODE REVIEW

**Comment by freak4pc** [comment]
Thanks for the PR @kcramer ! In that case I think we should actually remove that line, since it doesn't have the same meaning anymore.

Might be worth adding `catchErrorJustReturn` vs `replaceError(with:)`. 

WDYT ?

**Comment by kcramer** [comment]
I removed ```ifEmpty``` and as you suggested replaced ```just + catch``` for ```catchErrorJustReturn``` with ```replaceError(with:)```.

I searched the Combine documentation again and I don't see an equivalent to ```ifEmpty```.  I think removing ```ifEmpty``` is best unless you wanted to list all the operators in RxSwift that don't have an analog in Combine.

**Comment by kcramer** [comment]
I regenerated the files.  I did notice that generate.rb failed because it referenced a purple method which could not be found.  I changed it to blue and it worked.

Did you want to include RxSwift methods with no equivalent in Combine?  Otherwise, I think these changes are good.

**Comment by freak4pc** [comment]
Thanks - that's actually super weird, it worked for me here. Did the other colors in the script work well for you ? Regardless, looks great. Thank you!

**Comment by freak4pc** [comment]
Tried on a new mac and the puprle thing was causing issues for me as well - swapped for `magenta` and it seems fine now ... Thank you!

**Comment by kcramer** [comment]
Glad you have it working.  I did check and the standard colorize library doesn't have the purple color.  I guess you added it or another gem with it.

**Comment by freak4pc** [comment]
Yeah it's quite interesting since I didn't have anything installed, but who knows. Thanks anyways for catching that! A clear setup and perspective is always a great bug catcher 🐛

**Comment by kcramer** [comment]
My machine was apparently the perfect blank slate because I had not re-installed Ruby and its tools after I re-installed macOS. 😃

**Pull request merged**
