### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dp221125**
Issue [#13]

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey @dp221125, please read the Contribution Guide. You need to update the YAML file and run the regeneration script.

**Comment by dp221125** [comment]
I'm Sorry. 
I'm bundle install, and run script. but i got a error
"./generate.rb:4:in `<main>': undefined method `error' for main:Object (NoMethodError)"

**Comment by freak4pc** [comment]
can you run `ruby generate.rb` instead of running with `./` ?

**Comment by dp221125** [comment]
Umm..I got a same error..

**Comment by freak4pc** [comment]
It shouldn't fail but the fact it does means you don't have csv2md installed. Are you sure you properly ran `bundle install` ? 

Can you manually open the ruby script and remove the line that starts with `error(...` and try running it again?

**Pull request closed without merging**
