### PR TITLE
Add Empty/Never

### PR DESCRIPTION
**Pull request by stephencelis**
I believe `Publishers.Empty` handles these cases.

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey Stephen, Thanks :) 
Could you run `./generate.rb` please?

**Comment by stephencelis** [comment]
Ah I don't have the repo checked out :) Editing on my phone. Also just added `Timer.publish`.

**Comment by freak4pc** [comment]
Ok, don't worry about it :) I'll merge and add it on my end.

**Comment by freak4pc** [comment]
I don't have the latest beta but is Timer.publish actually interval, or timer? Does it start emitting immediately, or only after the first timespan ?

**Comment by freak4pc** [comment]
I had a friend try the following code and it emits nothing: 

```
Timer.publish(every: 0.1, on: .main, in: .default)
     .print()
     .sink { _ in }
```

Might be related to backpressure but I don't know much about it in Combine, yet. Have you tried Timer.publish ?

**Pull request merged**
