### PR TITLE
fix flatMapFirst

### PR DESCRIPTION
**Pull request by hmhv**

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey @hmhv - that looks great, thanks for the catch. 

I was only wondering - flatMapFirst says: 

>  If element is received while there is some projected observable sequence being merged it will simply be ignored.

Did you confirm `maxPublishers: 1` has the same behavior where it drops streams during the processing of a previous one?

**Comment by hmhv** [comment]
What about this?

```
maxPublishers
The maximum number of publishers produced by this method.
```
https://developer.apple.com/documentation/combine/publisher/3204712-flatmap

**Comment by freak4pc** [comment]
That piece of docs isn't clear enough to be sure, so I tested this.
There is one key difference between RxSwift and Combine in this sense - and that's backpressure.

Here's the RxSwift example:

image

Note that every 3 seconds - the specific element emitted from the upstream is processing and others are "dropped" (like said in the docs)

Here's the Combine example:

image

Note that the upstream doesn't "drop items" at all - but never actually produces them since backpressure prevents the upstream from producing more elements. In this sense it's more like a concat since the flatMap is forced to complete before the upstream can product more elements. 

I'm OK with listing it as a parallel even though ... in essence it's not too similar in behavior. What do you think ?

**Comment by freak4pc** [comment]
Messing with this a bit more - I wouldn't say this is like flatMapFirst.

I just realized `Observable.merge(maxConcurrent: 1)` is really the parallel of `flatMap(maxPublishers: .max(1))`.

**Comment by hmhv** [comment]
Thank you for your example. you are right.
`flatMap(maxPublishers: .max(1))` is not ignored element

**Comment by freak4pc** [comment]
This is still a very good point though, so I've added it in 416ec0754efc796c26b2fdb416839378f453e06c

**Pull request closed without merging**
